IF (
    ISINSCOPE ( 'Product'[Product] ),
    VAR SALESAMOUNCURRENTPRODUCT = [SALESAMOUNT]
    VAR PRODUCTRANK =
        RANKX ( ALLSELECTED ( 'PRODUCT'[Product] ), [SALESAMOUNT],  )
    VAR RESULT =
        IF ( NOT ISBLANK ( SALESAMOUNCURRENTPRODUCT ), PRODUCTRANK )
    RETURN
        result
)